### ISSUE TITLE
Signature Regeneration

### ISSUE THREAD

**Issue by rsiddle** [cameron-martin/private_pub#1]
I've got a vanilla setup - FAYE is working and listening on port 9292. 
The environment variables are set along with 

```
# messages/index.html.erb
<%= setup_private_pub %>
<%= sign_private_pub do |p|
  p.subscribe '/messages/new', '/messages/spam'
  p.publish '/messages/create'
end %>
```

```
# create.js.erb
private_pub.subscribe("/messages/new", function(data, channel) {
  $("#chat").append(data.message);
});
$("new_message")[0].reset();
```

It just keeps returning this particular error https://github.com/cameron-martin/private_pub/blob/master/app/assets/javascripts/private_pub.js#L135

Would you be able to include in the readme how to handle that? I'm not entirely sure where to use "PrivatePub.generateSignature" to regenerate the solution.

**Comment by cameron-martin** [comment]
Does it return that error when the page first loads, or only after the initial signature outputted by `sign_private_pub` has expired? The first case would mean something is going wrong. In the second case, you can get signature regeneration by overridding the `generateSignature` method on `private_pub` to grab signatures from `/signatures`.

``` javascript
private_pub.generateSignature = function (channel, action) {
  return Promise.resolve($.ajax({
    url: '/signatures',
    type: 'POST',
    data: { channel: channel, _action: action }
  }));
}
```

Then you need to make `/signatures` return new signatures. Authorization should be added here as required.

``` ruby
class SignaturesController < ApplicationController
  def create
    channel, action = params.values_at(:channel, :_action)

    signature = PrivatePub::Signature.new(channel: channel, action: action)

    respond_to do |format|
      format.json { render json: signature.to_hash  }
    end
  end
end
```

And add an appropriate route

``` ruby
  resources :signatures, only: [:create]
```

I will add this to the readme, and also make it easier to setup so the user doesn't have to paste in as much boilerplate code.

As a side-note, it is also possible to omit the `sign_private_pub` part, and it will grab signatures from `/signatures` right away. This means extra calls to the server, but you only have to have authorization logic for signatures in one place.

**Comment by cameron-martin** [comment]
Can I close this issue now?
